<?php

namespace Tests\Browser;

use Illuminate\Foundation\Testing\DatabaseMigrations;
use Laravel\Dusk\Browser;
use Tests\DuskTestCase;

class AuthenticationTest extends DuskTestCase
{
    protected static $migrationRun = false;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        if (!static::$migrationRun){

        $this->artisan('migrate:refresh');
        $this->artisan('db:seed');
        static::$migrationRun = true;
        }
    }


    /** @test */
    public function it_asserts_that_user_can_login()
    {
        $this->browse(function (Browser $browser) {
            $browser->visit('/login')
                    ->assertSee('Login Form')
                    ->type('email', 'komron.yusufjonovich@gmail.com')
                    ->type('password', '250399ky')
                    ->press('Login')
                    ->assertPathIs('/home')
                    ->assertSee('Dashboard')
                    ->assertAuthenticated();
        });
    }

    /** @test */
//    public function it_asserts_that_user_can_logout()
//    {
//        $this->browse(function (Browser $browser) {
//            $browser->loginAs('komron.yusufjonovich@gmail.com')
//                    ->visit('/home')
//                    ->clickLink('Logout')
//                    ->assertGuest();
//
//        });
//    }

    /** @test */
    public function it_asserts_that_user_can_login_fails()
    {
        $this->browse(function (Browser $browser) {
            $browser->visit('/login')
                ->assertSee('Login Form')
                ->type('email', 'komron.yusufjonovich@gmail.com')
                ->type('password', '250399')
                ->press('Login')
                ->assertPathIs('/login')
                ->assertSee('These credentials do not match our records.')
                ->assertsElementHasClass('input[name="email"]', 'is-invalid');
        });
    }
}
